# Generated by Django 4.2.21 on 2025-05-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("info", models.TextField()),
                (
                    "watering_frequency",
                    models.PositiveIntegerField(help_text="Irrigation frequency (day)"),
                ),
                (
                    "fertilizing_frequency",
                    models.PositiveIntegerField(
                        help_text="Fertilization frequency (days)"
                    ),
                ),
                ("light_preference", models.CharField(max_length=100)),
                (
                    "ideal_temperature",
                    models.IntegerField(help_text="Ideal temperature (°C)"),
                ),
            ],
        ),
    ]
