# Generated by Django 4.2.21 on 2025-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_userplant"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplant",
            name="last_reminder_sent",
            field=models.DateField(blank=True, null=True),
        ),
    ]
